#!/usr/bin/env bash
# Starts the ComfyUI backend on port 8188 using the project venv.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"

# First run: wire the shared ~/models tree into ComfyUI so downloads live
# outside the repo. Never overwrites an existing file (yours may add more paths).
PATHS_FILE="$ROOT/comfyui/extra_model_paths.yaml"
if [ ! -f "$PATHS_FILE" ]; then
  mkdir -p "$HOME/models"/{checkpoints,diffusion_models,text_encoders,vae,loras}
  cat > "$PATHS_FILE" <<EOF
# Generated by scripts/comfy.sh — points ComfyUI at the shared ~/models tree.
# Safe to edit; this file is only created when missing.
safelight_models:
  base_path: $HOME/models
  checkpoints: checkpoints
  diffusion_models: diffusion_models
  unet: diffusion_models
  text_encoders: text_encoders
  clip: text_encoders
  vae: vae
  loras: loras
EOF
  echo "created $PATHS_FILE (models root: $HOME/models)"
fi

cd "$ROOT/comfyui"
exec .venv/bin/python main.py \
  --listen 127.0.0.1 \
  --port "${COMFY_PORT:-8188}" \
  --enable-cors-header "http://localhost:3001" \
  --preview-method auto \
  --output-directory "$ROOT/outputs" \
  --input-directory "$ROOT/inputs" \
  "$@"
