allowBuilds:
  '@google/genai': false
  better-sqlite3: set this to true or false
  protobufjs: false
  sharp: false
  unrs-resolver: false
fetchRetries: 6
fetchTimeout: 600000
networkConcurrency: 4
onlyBuiltDependencies:
  - better-sqlite3
